const { default: mongoose } = require("mongoose");

const groupSchema=new mongoose.Schema({
   
// Objectid will be auto generated by mongodb.
   
    groupId:{
        type:String,
        require:true
    },

    groupMentor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        require:true
    },

    projectTitle:{
        type:String,
        require:true
    },

    projectType:{
        type:String,
        enum:["cloud&devops","cybersecurity","dataScience","fullStack","java","python","react","webDevelopment"],
    },

    groupMembers:[{
        type:mongoose.Schema.Types.ObjectId ,
        ref:"User",
        require:true
    }],
})


module.exports=mongoose.model("Group",groupSchema);