const { default: mongoose } = require("mongoose");

const ReportSchema=new mongoose.Schema({

// task_id will be auto generated by mongodb

   
    groupId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Group",
        require:true
    },
    
    file:{
        type:String,  // link of the file of drive
        require:true
    },

    isCorrect:{
        type:Boolean,
        require:true
    },

    remarks:{
        type:String,
        require:true
    }
})


module.exports=mongoose.model("Report",ReportSchema);